spring:
  application:
    name: event-ticketing-system
    group: com.iit.event.ticketing.system
    version: 1.0.0
  lifecycle:
    timeout-per-shutdown-phase: 1m
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:mem:ticketing
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
  servlet:
    context-path: /api
  shutdown: graceful

management:
  endpoints:
    web:
      base-path: /management
    access:
      default: read_only
  endpoint:
    health:
      access: read_only

logging:
  level:
    com.iit.event.ticketing.system: debug
