spring:
  application:
    name: event-ticketing-system
  lifecycle:
    timeout-per-shutdown-phase: 1m
  threads:
    virtual:
      enabled: true

server:
  port: 8080
  servlet:
    context-path: /api
  shutdown: graceful

management:
  endpoints:
    web:
      base-path: /management
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    com.iit.event.ticketing.system: trace

ticketing:
  total-tickets: 0
  ticket-release-rate: 0
  customer-retrieval-rate: 0
  max-ticket-capacity: 0
